version: '3.8'

networks:
  mysql-api-delphi_mysql_for_delphi:
    external: true

services:
  api_for_delphi:
    container_name: api_for_delphi
    build: .
    entrypoint: sh -c "yarn && yarn start:dev"
    ports:
      - 4000:3000
    volumes:
      - .:/home/node/api
    networks:
      - mysql-api-delphi_mysql_for_delphi
